### ISSUE TITLE
Test failures with Java 21 

### ISSUE THREAD

**Issue by vpa1977** [dakrone/cheshire#205]
The following tests fail when building with Java 21:

```
[INFO] Running com.fasterxml.classmate.TestMemberResolver
[ERROR] Tests run: 10, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.03 s <<< FAILURE! - in com.fasterxml.classmate.TestMemberResolver
[ERROR] testFilters(com.fasterxml.classmate.TestMemberResolver) Time elapsed: 0.002 s <<< FAILURE!
junit.framework.AssertionFailedError: expected:<12> but was:<13>
 at com.fasterxml.classmate.TestMemberResolver.testFilters(TestMemberResolver.java:228)

[ERROR] testIncludeObject(com.fasterxml.classmate.TestMemberResolver) Time elapsed: 0.004 s <<< FAILURE!
junit.framework.AssertionFailedError: expected:<12> but was:<13>
 at com.fasterxml.classmate.TestMemberResolver.testIncludeObject(TestMemberResolver.java:217)

[INFO] Running com.fasterxml.classmate.TestReadme
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in com.fasterxml.classmate.TestReadme
[INFO] Running com.fasterxml.classmate.AnnotationInclusionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.fasterxml.classmate.AnnotationInclusionTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] AnnotationsTest.annotationsToSize:75
[ERROR] TestMemberResolver.testFilters:228 expected:<12> but was:<13>
[ERROR] TestMemberResolver.testIncludeObject:217 expected:<12> but was:<13>
[INFO]
[ERROR] Tests run: 225, Failures: 3, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by lread** [comment]
@dakrone, this looks like a report from Jackson itself?
Anyhoo, we do test on JDK21 on CI and cheshire tests pass.
Probably can close this one?

**Comment by dakrone** [comment]
Closing, shouldn't be a problem any more.
